web:
  image: nginx:latest
  ports:
      - "8080:80"
  volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
  links: 
    - php
  
    
php: 
  image: php:7-fpm
  volumes:
    - ./app:/app

composer:
  image: composer:latest
  entrypoint: composer install
  command: "chmod -Rf 755 /app/vendor"
  volumes: 
    - ./app:/app