version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    working_dir: /app
    volumes:
      - ./app:/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - php
      
  php: 
    build: 
      dockerfile: ./docker/php.dockerfile
      context: .
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
 

  composer:
    image: composer:latest
    volumes: 
      - ./app:/app
    working_dir: /app
    entrypoint: composer install
    command: chmod 755 vendor/

  mysql:
    image: mysql:5.7
    container_name: db-mysql
    working_dir: /app
    restart: always
    volumes: 
      - ./app:/app
    ports: 
      - "8000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=vanillaframework
      - MYSQL_PASSWORD=password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links: 
      - mysql
    ports:
      - "3000:80"
    environment:
      - PMA_ARBITRARY=1
